In [2]:
import cv2
import tensorflow as tf 
from tensorflow.keras.models import load_model
from pygame import mixer
import numpy as np

pygame 2.1.2 (SDL 2.0.18, Python 3.10.2)
Hello from the pygame community. https://www.pygame.org/contribute.html


In [3]:
face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')
eye_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_eye.xml')
model = load_model(r'D:\sem V\DL\Proj\model\model_resnet.h5')

In [5]:
mixer.init()
sound= mixer.Sound(r'D:\sem V\DL\Proj\alarm1.wav')
cap = cv2.VideoCapture(0)
Score = 0
while True:
    ret, frame = cap.read()
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    faces= face_cascade.detectMultiScale(gray, scaleFactor= 1.2, minNeighbors=3)
    eyes= eye_cascade.detectMultiScale(gray, scaleFactor= 1.1, minNeighbors=1)
    
    for (x,y,w,h) in faces:
        cv2.rectangle(frame,pt1=(x,y),pt2=(x+w,y+h), color= (255,0,0), thickness=3 )
        
    for (ex,ey,ew,eh) in eyes:
        
        # preprocessing steps
        eye= frame[ey:ey+eh,ex:ex+ew]
        eye= cv2.resize(eye,(80,80))
        eye= eye/255
        eye= eye.reshape(80,80,3)
        eye= np.expand_dims(eye,axis=0)  

        # preprocessing is done now model prediction
        prediction = model.predict(eye)
        print(prediction)
        # if eyes are closed
        if prediction[0][0]>0.30:
            Score+=1
            print(Score)
            if(Score>15):
                try:
                    sound.play()

                except:
                    pass
            
        # if eyes are open
        elif prediction[0][1]>0.90:
            Score-=1
            if (Score<5):
                Score=0
        
    cv2.imshow('frame',frame)
    if cv2.waitKey(33) & 0xFF==ord('q'):
        break
        
cap.release()
cv2.destroyAllWindows()

1/1 [==============================] - 0s 38ms/step
[[0.6310271  0.36897293]]
1
1/1 [==============================] - 0s 36ms/step
[[0.23494048 0.7650595 ]]
1/1 [==============================] - 0s 43ms/step
[[0.7692732  0.23072681]]
2
1/1 [==============================] - 0s 41ms/step
[[0.91062474 0.08937526]]
3
1/1 [==============================] - 0s 42ms/step
[[0.45248696 0.54751307]]
4
1/1 [==============================] - 0s 42ms/step
[[0.13373086 0.8662691 ]]
1/1 [==============================] - 0s 40ms/step
[[0.00843686 0.9915631 ]]
1/1 [==============================] - 0s 38ms/step
[[0.6423986  0.35760134]]
1
1/1 [==============================] - 0s 48ms/step
[[0.7976065  0.20239346]]
2
1/1 [==============================] - 0s 37ms/step
[[0.04611561 0.95388436]]
1/1 [==============================] - 0s 43ms/step
[[0.76954114 0.23045881]]
1
1/1 [==============================] - 0s 35ms/step
[[0.07302921 0.9269708 ]]
1/1 [==============================] - 0s 39ms/ste

1/1 [==============================] - 0s 36ms/step
[[0.00151577 0.9984843 ]]
1/1 [==============================] - 0s 35ms/step
[[0.36749822 0.6325018 ]]
18
1/1 [==============================] - 0s 40ms/step
[[0.38518274 0.61481726]]
19
1/1 [==============================] - 0s 38ms/step
[[0.00461002 0.99538994]]
1/1 [==============================] - 0s 39ms/step
[[0.6040416  0.39595842]]
19
1/1 [==============================] - 0s 36ms/step
[[0.15395811 0.8460419 ]]
1/1 [==============================] - 0s 36ms/step
[[2.137762e-04 9.997862e-01]]
1/1 [==============================] - 0s 36ms/step
[[0.16823477 0.8317652 ]]
1/1 [==============================] - 0s 39ms/step
[[0.14105015 0.85894984]]
1/1 [==============================] - 0s 41ms/step
[[0.09988603 0.900114  ]]
1/1 [==============================] - 0s 41ms/step
[[0.02128319 0.9787168 ]]
1/1 [==============================] - 0s 36ms/step
[[0.4056262 0.5943737]]
17
1/1 [==============================] - 0s 35ms/ste

1/1 [==============================] - 0s 41ms/step
[[3.8655158e-04 9.9961346e-01]]
1/1 [==============================] - 0s 35ms/step
[[0.76601094 0.23398905]]
1
1/1 [==============================] - 0s 38ms/step
[[0.10013483 0.89986515]]
1/1 [==============================] - 0s 36ms/step
[[0.03969851 0.96030146]]
1/1 [==============================] - 0s 35ms/step
[[0.02906156 0.97093844]]
1/1 [==============================] - 0s 36ms/step
[[0.10688961 0.8931104 ]]
1/1 [==============================] - 0s 34ms/step
[[0.01581657 0.98418343]]
1/1 [==============================] - 0s 39ms/step
[[0.9823821  0.01761787]]
1
1/1 [==============================] - 0s 36ms/step
[[0.4111482  0.58885187]]
2
1/1 [==============================] - 0s 37ms/step
[[0.35276392 0.64723605]]
3
1/1 [==============================] - 0s 41ms/step
[[0.10470466 0.89529526]]
1/1 [==============================] - 0s 38ms/step
[[0.5322455  0.46775442]]
4
1/1 [==============================] - 0s 39ms/s